server:
  port: 9009

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/churchsoft_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Lee10121}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

aws:
  s3:
    accessKey: ${AWS_S3_ACCESS_KEY}
    secretKey: ${AWS_S3_SECRET_KEY}
    bucketName: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

app:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
